### PR TITLE
New Katana and Laser Gun textures.

### PR DESCRIPTION
**Pull request by Tenebris11**
I decided I might submit my personal textures for the katana to make it match the vanilla TiC theme better.  I will also be working on the laser gun if you are interested.

### CODE REVIEW

**Comment by Tenebris11** [comment]
Additionally, I could try to make textures for the modifiers on the Katana, as it seems to be lacking quite a few.

**Comment by Landmaster** [comment]
> Additionally, I could try to make textures for the modifiers on the Katana, as it seems to be lacking quite a few.

@Tenebris11 Sure, please do.

**Comment by Tenebris11** [comment]
Added the Katana modifiers

**Comment by Tenebris11** [comment]
Do you want me to create textures for the Laser Gun modifiers?

**Comment by Landmaster** [comment]
@Tenebris11 Don't create the textures for the Laser Gun modifiers just yet; there are a few minor things that I still need to test for this PR.

**Comment by Tenebris11** [comment]
Ok, just let me know if and when.

**Comment by Landmaster** [comment]
I reoriented the laser gun textures so that they point up instead of down.

**Comment by Landmaster** [comment]
Looks good to me.

**Comment by Landmaster** [comment]
@Tenebris11 You may add in the laser gun modifier textures now in a new pull request. Thanks for your contributions!

**Comment by Tenebris11** [comment]
Ok, I'll work on them as soon as possible.

**Pull request merged**
